site_name: Home - UNL UAV

nav:
  - Home: index.md
  - About Us:
    - Getting Started: welcome.md
    - People: people.md
    - Teams: teams.md
  - More Info:
    - Contact Us: contact.md
    - Resources: resources.md
    - Credits: credits.md

theme:
  name: readthedocs
  custom_dir: custom_theme/

copyright: UNL-UAV
site_description: UNL Aerospace UAV IARC Team Page

markdown_extensions:
  - attr_list

plugins:
  - search
  - git-revision-date:
      as_datetime: true
dev_addr: 127.0.0.1:8080